### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by cschol** [teletypist/stochasm#5]
Hi @teletypist,

Could you please clarify the license of this plugin?

> Use and distribution of this plugin requires the permission of the author in writing.

- It says "**use** [...] of this plugin requires the permission of the author in writing": what does this mean?
- Are you OK with it being added to the VCV Rack `community` repository, i.e. the source code being distributed via that repository as a `git submodule`?

Thank you!

**Comment by teletypist** [comment]
Yeah, those licence terms were a stop gap while I figured out what open source licence I wanted to go with. Then I promptly forgot about it while focusing on the plugin itself.

I’ve since decided to change the licence over to MIT.

**Comment by cschol** [comment]
Thank you!
